In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("new_file3.csv")

C:\Users\Kipplouser1\AppData\Local\Temp\ipykernel_3464\3677640229.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("new_file3.csv")

In [9]:
# Drop email which has NULL values
df2= df[df['Personal_Email'].notna()]

In [10]:
# Drp values which has no phone number
df2.dropna(subset=['phone_numbers'])

,first_name,last_name,linkedin_url,phone_numbers,Personal_Email
anthony spina,anthony,spina,linkedin.com/in/anthony-spina-823aab15,"['+12036519583', '+18605120332']",'tpaws123@aol.com'
david sainte,david,sainte,linkedin.com/in/davidsainte,"['+15167656068', '+15165241406', '+15169659965...",'ecb159@yahoo.com'
eric bram,eric,bram,linkedin.com/in/eric-c-bram-b2973518,['+15139220444'],"'melissascarpace@msn.com', 'melissascarpace@..."
maria frallicciardi,maria,frallicciardi,linkedin.com/in/maria-frallicciardi-53b5645b,['+13059689004'],"'pwood865@gmail.com', 'pauljameswood@hotmail..."
steven overturf,steven,overturf,linkedin.com/in/steven-overturf-14762192,"['+19315515574', '+18307733826', '+19316458110']",'mayorih7@gmail.com'
...,...,...,...,...,...
don mcmillan,don,mcmillan,linkedin.com/in/don-mcmillan-7a107021,['+12105733288'],"'nybooboo78@ameritech.net', 'nybooboo@aol.co..."
dievina navarrete,dievina,navarrete,linkedin.com/in/dievina-navarrete-55030a15,"['+17074212117', '+17078530962', '+17073379252...",'fisherdgf@gmail.com'
al grabowski,al,grabowski,linkedin.com/in/al-grabowski-2b132234,['+16023232560'],"'colinmcbride@sbcglobal.net', 'colinmcbride@..."
jonathan gibbs,jonathan,gibbs,linkedin.com/in/jonathan-gibbs-17b3b611,['+16785020827'],'jscolla@yahoo.com'
bruce coombs,bruce,coombs,linkedin.com/in/bruce-coombs-a6560214,"['+19133100443', '+14354064166']",'ahsegal@yahoo.com'

In [11]:
df2

,first_name,last_name,linkedin_url,phone_numbers,Personal_Email
anthony spina,anthony,spina,linkedin.com/in/anthony-spina-823aab15,"['+12036519583', '+18605120332']",'tpaws123@aol.com'
david sainte,david,sainte,linkedin.com/in/davidsainte,"['+15167656068', '+15165241406', '+15169659965...",'ecb159@yahoo.com'
eric bram,eric,bram,linkedin.com/in/eric-c-bram-b2973518,['+15139220444'],"'melissascarpace@msn.com', 'melissascarpace@..."
maria frallicciardi,maria,frallicciardi,linkedin.com/in/maria-frallicciardi-53b5645b,['+13059689004'],"'pwood865@gmail.com', 'pauljameswood@hotmail..."
steven overturf,steven,overturf,linkedin.com/in/steven-overturf-14762192,"['+19315515574', '+18307733826', '+19316458110']",'mayorih7@gmail.com'
...,...,...,...,...,...
don mcmillan,don,mcmillan,linkedin.com/in/don-mcmillan-7a107021,['+12105733288'],"'nybooboo78@ameritech.net', 'nybooboo@aol.co..."
dievina navarrete,dievina,navarrete,linkedin.com/in/dievina-navarrete-55030a15,"['+17074212117', '+17078530962', '+17073379252...",'fisherdgf@gmail.com'
al grabowski,al,grabowski,linkedin.com/in/al-grabowski-2b132234,['+16023232560'],"'colinmcbride@sbcglobal.net', 'colinmcbride@..."
jonathan gibbs,jonathan,gibbs,linkedin.com/in/jonathan-gibbs-17b3b611,['+16785020827'],'jscolla@yahoo.com'
bruce coombs,bruce,coombs,linkedin.com/in/bruce-coombs-a6560214,"['+19133100443', '+14354064166']",'ahsegal@yahoo.com'

In [12]:
df2.to_csv("emailandphone.csv")